[UI] userSelect css bug
jupyterlab/jupyterlab-git pull request #1062
Opened 2021-12-22 08:38 UTC by himanshu007-creator

resolves #1060

2021-12-22 23:24 UTC, krassowski commented on src/style/BranchMenu.ts
> +    userSelect: null,
```suggestion
    userSelect: null
```

2021-12-23 09:30 UTC, fcollonval requested changes
Thanks @himanshu007-creator 

I'm sorry the correct value is `'none'` not `null`. Would you mind correcting it?

Could you also add that style in the following block for the files list in the history tab:

https://github.com/fcollonval/jupyterlab-git/blob/2343024abe16f56700a2c4a6d7b99dc366c60a11/src/style/SinglePastCommitInfo.ts#L38

2021-12-23 09:30 UTC, fcollonval commented on src/style/BranchMenu.ts
> +    userSelect: null
```suggestion
    userSelect: 'none'
```

2021-12-23 09:30 UTC, fcollonval commented on src/style/FileItemStyle.ts
> +    userSelect: null,
```suggestion
    userSelect: 'none',
```

2021-12-23 11:16 UTC, himanshu007-creator commented on src/style/BranchMenu.ts
> +    userSelect: null
ill do it

2022-01-10 07:56 UTC, fcollonval approved these changes
Thanks a lot @himanshu007-creator and sorry for the late answer

2022-01-10 07:56 UTC, merged