Refresh open file on pull
jupyterlab/jupyterlab-git pull request #1090
Opened 2022-03-15 22:36 UTC by ajbozarth

Currently doing a pull does not update the contents of open files
like switching branches does.

This runs the same function to update files as switching branches but instead of diffing the branches it diffs the previous top commit to the new HEAD. 

Fixes #1086

2022-03-16 15:44 UTC, fcollonval requested changes
Thanks @ajbozarth 

There is a bug in the existing method. And the call order needs to be set up a bit differently to ensure we get the correct value.

1. Store the top commit hash as we don't control its update - it may happen after the pull and before the changed files are requested.

2. We should wait for the task

```
const data = await this._taskHandler.execute
```

3. Get the changed files and revert

4. await for `this.refreshBranch()`

2022-03-16 15:50 UTC, fcollonval commented
Looking at the test failure, we need to check if `_currentBranch` is null or not :wink:

2022-03-18 21:16 UTC, ajbozarth commented
@fcollonval I made the updates you suggested. I original had the top commit stored first, but I stream-lined my changes when I found that the `refreshBranch` function call is what updated it. I do believe storing it first is still the safer plan though, even with adding the awaits

2022-03-21 16:53 UTC, fcollonval approved these changes
Thanks a lot @ajbozarth

2022-03-21 16:53 UTC, merged

2022-03-22 12:17 UTC, fcollonval commented
Release is in progress @ajbozarth