Add the feature for comparing two arbitrary commits
jupyterlab/jupyterlab-git pull request #1108
Opened 2022-04-14 05:18 UTC by quachtridat

## Summary

This PR resolves #985 by implementing the necessary components and logic that will allow users to select two commits in the *History* tab and see the Git diff for every changed file.

## Details

*W.I.P.*

## Caveats

The commit comparison box can be collapsed, but cannot be resized for now.

## Demos

*W.I.P.*

## Notes

This PR may need more tests.

## Linked issues

#985

2022-04-15 07:04 UTC, fcollonval requested changes
Thanks @quachtridat and @ZeshanFayyaz 

I mainly have suggestions for a better wording (using reference/challenger instead of lhs/rhs) and a small rework to avoid storing twice the same information in the panel state.

2022-04-15 07:04 UTC, fcollonval commented on src/style/PastCommitNode.ts
> +  borderLeft: '3px solid darkred'
Could you try with 
```suggestion
  borderLeft: '3px solid var(--jp-git-diff-deleted-color)'
```

2022-04-15 07:04 UTC, fcollonval commented on src/style/PastCommitNode.ts
> +  borderLeft: '3px solid darkgreen'
```suggestion
  borderLeft: '3px solid var(--jp-git-diff-added-color)'
```

2022-04-15 07:35 UTC, quachtridat commented on jupyterlab_git/git.py
> +            if len(linesplit) == 3:
> Why is this test required? In which case are those information missing?

I have not manually tested without this, but in early development of this feature I got an error without that line (and it was `IndexError` if I remember correctly), and no error with that line.

2022-04-15 07:38 UTC, fcollonval commented on jupyterlab_git/git.py
> +            if len(linesplit) == 3:
thanks @quachtridat would you mind adding a else condition that log at debug level the _broken_ line?

2022-04-15 07:41 UTC, quachtridat commented on src/tokens.ts
> +    rhs: ISingleCommitInfo;
That means we should just pass `referenceCommit`, `challengerCommit` and `comparison` one-by-one as props for `CommitComparisonBox`?

2022-04-15 07:44 UTC, quachtridat commented on src/components/CommitComparisonBox.tsx
> +  ) => (event: React.MouseEvent<HTMLLIElement, MouseEvent>) => void;
TODO: docstring.
@ZeshanFayyaz

2022-04-15 07:45 UTC, quachtridat commented on src/components/CommitComparisonBox.tsx
> +  ) => (event: React.MouseEvent<HTMLLIElement, MouseEvent>) => void;
TODO: docstring.
@ZeshanFayyaz

2022-04-15 07:46 UTC, quachtridat commented on jupyterlab_git/git.py
> +            if len(linesplit) == 3:
> thanks @quachtridat would you mind adding a else condition that log at debug level the _broken_ line?

Sure!
@ZeshanFayyaz we might as well investigate this.

2022-04-20 06:49 UTC, fcollonval commented on jupyterlab_git/handlers.py
>          POST request handler, fetches differences between commits & current working
```suggestion
        POST request handler, fetches differences between two states
```

2022-04-20 07:27 UTC, fcollonval approved these changes
Thanks a lot @quachtridat and @ZeshanFayyaz 

This is a great addition

2022-04-20 08:09 UTC, merged

2022-04-25 11:50 UTC, fcollonval commented
@all-contributors please add quachtridat for code

2022-04-25 11:51 UTC, fcollonval commented
@all-contributors please add @ZeshanFayyaz for code