add current branch name on status bar
jupyterlab/jupyterlab-git pull request #1131
Opened 2022-06-10 17:47 UTC by BoscoCHW

@fcollonval 
Added current branch name on the status bar
I managed to style it but I'm not sure how to center the text vertically.
I should make the parent element a flex box and do align-item: center but I don't know how to select the parent class.
Also I'm not sure how to change the padding of the git icon so that the text could be closer to the icon.

Another issue is when navigate to another repo (change file directory), the branch name stays unless you click on the git extension icon on the left menu bar, which is a bit weird.

2022-06-12 17:24 UTC, fcollonval requested changes
Thanks @BoscoCHW 

> Added current branch name on the status bar I managed to style it but I'm not sure how to center the text vertically. I should make the parent element a flex box and do align-item: center but I don't know how to select the parent class. Also I'm not sure how to change the padding of the git icon so that the text could be closer to the icon.

You can add a class in `StatusWidget` (the parent element) within the [constructor](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/components/StatusWidget.tsx#L27) by adding the following line:

```ts
this.addClass('jp-git-StatusWidget')
```

Note: by design it is not possible to select parent of an element with CSS selectors.

> Another issue is when navigate to another repo (change file directory), the branch name stays unless you click on the git extension icon on the left menu bar, which is a bit weird.

The default behavior is to not refresh the Git model status when the sidebar is hidden to avoid useless calls to the backend. You could solve this by forcing refreshing the branch calling [GitExtension.refreshBranch](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/model.ts#L981) when we set a [new repository](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/index.ts#L151).

2022-06-12 17:24 UTC, fcollonval commented on src/components/StatusWidget.tsx
> +            )}
You should place this outside the `UseSignal` component as it does not need to be refreshed if the credentials status of the extension changes.

But you should wrap it in another `UseSignal` component to listen to `this._model.headChanged` to react when the git head is changed.

2022-06-14 00:08 UTC, BoscoCHW commented
@fcollonval 

I managed to style the status widget by adding a class like you suggested, but I was unable to reduce the right-padding of the git icon on the status bar because I'm afraid overriding the pre-set would lead to unexpected results.

2022-06-14 17:28 UTC, fcollonval commented on src/components/StatusWidget.tsx
> +        <UseSignal signal={this._model.headChanged}>
:+1:

2022-06-17 18:16 UTC, fcollonval requested changes
Let's remove the star next to the branch name. And it is good to go.

2022-06-17 18:16 UTC, fcollonval commented on src/components/StatusWidget.tsx
> +                {this._model.currentBranch.name}*
Let's remove the star for now.

```suggestion
                {this._model.currentBranch.name}
```

2022-06-17 19:00 UTC, fcollonval approved these changes
Thanks @BoscoCHW

2022-06-17 19:00 UTC, merged