620
jupyterlab/jupyterlab-git pull request #1184
Opened 2022-11-15 15:42 UTC by sheezaaziz

https://github.com/jupyterlab/jupyterlab-git/issues/620

2022-11-30 10:07 UTC, fcollonval requested changes
Thanks @sheezaaziz I have a few suggestions.

2022-11-30 10:07 UTC, fcollonval commented on src/commandsAndMenu.tsx
> +              }
Could you create a static method in `PreviewMainAreaWidget` like `pin(widget: Widget)` that will do that?

2022-11-30 10:07 UTC, fcollonval commented on src/components/diff/PreviewMainAreaWidget.ts
> +  static previewWidget: PreviewMainAreaWidget | null = null;
Let's make this protected

```suggestion
  protected static previewWidget: PreviewMainAreaWidget | null = null;
```

2022-11-30 10:07 UTC, fcollonval commented on src/commandsAndMenu.tsx
> +          setTimeout(() => {
Let's add some explanation about the need for `setTimeout`

```suggestion
          // We need to wait for the tab node to be inserted in the DOM
          setTimeout(() => {
```

2022-12-05 16:35 UTC, fcollonval requested changes
Thank @sheezaaziz 

Two small things and we are good to go.

2022-12-05 16:35 UTC, fcollonval commented on style/diff-nb.css
> +
Would you mind placing this block at the end of `style/base.css`.

2022-12-05 16:35 UTC, fcollonval commented on src/components/diff/PreviewMainAreaWidget.ts
> +      };
Almost correct, we also want to remove the click listener once it has been triggered or when the diff view is disposed:

```suggestion
      const onClick = () => {
        tabTitle.classList.remove('jp-git-tab-mod-preview');
        tabTitle.removeEventListener('click', onClick, true);
        if (PreviewMainAreaWidget.previewWidget === diffWidget) {
          PreviewMainAreaWidget.previewWidget = null;
        }
      };
      
      tabTitle.addEventListener('click', onClick, true);
      diffWidget.disposed.connect(() => {
        tabTitle.removeEventListener('click', onClick, true);
      });
```

2022-12-08 08:30 UTC, fcollonval reviewed
Thanks a lot @sheezaaziz 

I tested and look again at the code. This is great. I rerun the tests failing hoping it is a random error.

2022-12-08 08:52 UTC, fcollonval approved these changes

2022-12-08 08:52 UTC, merged

2022-12-08 08:53 UTC, fcollonval commented
https://github.com/all-contributors please add @sheezaaziz for code

2022-12-08 08:54 UTC, fcollonval commented
@all-contributors please add @sheezaaziz for code

2022-12-24 13:48 UTC, krassowski commented
Great work here, it is a nice feature to have!
- Could we add a setting to disable this behaviour? It seems that https://github.com/jupyterlab/jupyterlab-git/issues/620 proposed adding this as an opt-in setting.
- When I move the diff to another spit panel (say to the right):
   - the italic style in tab bar disappears (probably the class does not stick after reattaching in another panel)
   - if I open another diff the old diff in right panel gets closed and reopened in the left panel. I find this annoying, I guess it was not intended.
- I had no idea what italic style means before looking at the docs; it would be helpful if there was an explanation in the title, or maybe even a pin icon; a pin icon could be implemented as unicode prefix (📌) added to title