add context menu option to delete untracked files
jupyterlab/jupyterlab-git pull request #815
Opened 2020-10-31 18:55 UTC by ianhi

Closes: https://github.com/jupyterlab/jupyterlab-git/issues/687

Made a new command for this so we can present a warning dialog. Using the `docmanager:delete-file` command directly doesn't allow for a warning dialog.

2020-10-31 19:00 UTC, ianhi commented
![delete-untracked](https://user-images.githubusercontent.com/10111092/97787640-d00e4e00-1b89-11eb-9ecf-d46ead6c0f14.gif)

2020-11-01 16:26 UTC, fcollonval requested changes
Almost good to go.

You should wait on the command execution otherwise error may not be catch.

2020-11-01 16:26 UTC, fcollonval commented on src/commandsAndMenu.tsx
> +          app.commands.execute('docmanager:delete-file', {
```suggestion
          await app.commands.execute('docmanager:delete-file', {
```

2020-11-01 16:35 UTC, ianhi commented on src/commandsAndMenu.tsx
> +          app.commands.execute('docmanager:delete-file', {
Done - thanks!

2020-11-01 18:01 UTC, fcollonval approved these changes
Thanks LGTM!

2020-11-03 17:55 UTC, merged