Prevent empty JSON body from causing None error in git config endpoint
jupyterlab/jupyterlab-git pull request #959
Opened 2021-06-22 13:47 UTC by DarkmatterVale

### Notes
- Address #958 

### Tests
- `pytest jupyterlab_git`, verified all tests pass

2021-06-22 13:50 UTC, tleonhardt approved these changes

2021-06-23 06:56 UTC, fcollonval requested changes
Hey @DarkmatterVale thanks for the fix. I would suggest a slightly more robust approach to prevent this to happen in the future. Let me know what you think.

2021-06-23 06:56 UTC, fcollonval commented on jupyterlab_git/handlers.py
>          data = self.get_json_body()
I would set the default here. That will prevent future error if more information are looked for in data.

```suggestion
        data = self.get_json_body() or {}
```

2021-06-23 06:56 UTC, fcollonval commented on jupyterlab_git/handlers.py
> +        options = data.get("options", {}) if data else {}
```suggestion
        options = data.get("options", {})
```

2021-06-24 15:14 UTC, merged